name: Build & Deploy Spring Boot Docker Image (Gradle)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Add execution perms to gradlew
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker Image
      run: |
        REPOSITORY_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        REPOSITORY_NAME=${GITHUB_REPOSITORY##*/}
        REPOSITORY_NAME_LOWER=$(echo "$REPOSITORY_NAME" | tr '[:upper:]' '[:lower:]')
        docker build -t ghcr.io/$REPOSITORY_OWNER/$REPOSITORY_NAME_LOWER:latest .

    - name: Push the Docker Image to GitHub Container Registry
      run: |
        REPOSITORY_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        REPOSITORY_NAME=${GITHUB_REPOSITORY##*/}
        REPOSITORY_NAME_LOWER=$(echo "$REPOSITORY_NAME" | tr '[:upper:]' '[:lower:]')
        docker push ghcr.io/$REPOSITORY_OWNER/$REPOSITORY_NAME_LOWER:latest